apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - staging-issuer.yaml
patches:
  - target:
      kind: Ingress
      name: frontend
    path: ingress-patch.yaml
patchesStrategicMerge:
  - set-service-type.yaml
